SYMFONY := docker-compose exec php bin/console

#####################################
###                               ###
###    Docker-compose utilities   ###
###                               ###
#####################################

build:
	@echo 'build Dockerfiles into container'
	docker-compose build

## Start the environment
start:
	@echo 'Starting containers in dev mode'
	docker-compose up -d

stop:
	@echo 'Stop all docker containers'
	docker-compose down

kill:
	docker-compose kill
	docker-compose down --volumes --remove-orphans
	sudo rm -rf logs/*

ps:
	@echo 'List all containers managed by the environment'
	docker-compose ps

logs:
	@echo 'Follow logs generated by all containers from the containers creation'
	docker-compose logs -f

php: #Connect
	docker-compose exec php bash

db: #Connect
	docker-compose exec mysql bash

#####################################
###                               ###
###   Symfony commands utilities  ###
###                               ###
#####################################

cache:
	@echo 'clear the cache'
	$(SYMFONY) cache:clear
